### ISSUE TITLE
Functions needed

### ISSUE THREAD

**Issue by JasonWQWu** [JasonWQWu/DSA-SegTree#7]
Functions needed:
- [x] Read input
- [x] Build Tree
- [x] Find Max
- [x] Update value (Insert)
- [x] Search for # of cars (-1 if not found)
- [x] Output DOT file
- [x] Build UI

**Comment by Eric-Chin-URI** [comment]
We dont need search right? bc thats max

**Comment by JasonWQWu** [comment]
I think so. Can check that off.
